### ISSUE TITLE
`getLoadContext` does not execute when passed to `createRequestHandler`

### ISSUE THREAD

**Issue by juanpprieto** [netlify/remix-compute#94]
Hi @nickytonline 

I been trying to add a context property in the edge template without any luck.

```tsx
// server.js

import { createRequestHandler } from "@remix-run/netlify";
import * as build from "@remix-run/dev/server-build";

export const handler = createRequestHandler({
  build,
  mode: process.env.NODE_ENV,
  getLoadContext: (_, context) => {
    console.log('🤷 not being called....') 
    return { ...context, foo: 'bar' }
  }
});
```

I tried debugging it via the `/packages/demo-edge-site` but it seems to be broken:

```bash
/remix-compute/packages/edge-demo-site main* ❯ npm run dev                           12:17:07

> edge-demo-site@1.0.0 dev
> remix dev

Error: remix dev is not supported for custom servers.
    at Object.serve (/Users/jbaz/code-work/2023/remix-compute/node_modules/@remix-run/dev/dist/devServer/serve.js:41:11)
    at Object.dev (/Users/jbaz/code-work/2023/remix-compute/node_modules/@remix-run/dev/dist/cli/commands.js:215:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async dev (/Users/jbaz/code-work/2023/remix-compute/node_modules/@remix-run/dev/dist/cli/run.js:194:3)
    at async Object.run (/Users/jbaz/code-work/2023/remix-compute/node_modules/@remix-run/dev/dist/cli/run.js:477:7)
npm ERR! Lifecycle script `dev` failed with error:
npm ERR! Error: command failed
npm ERR!   in workspace: edge-demo-site@1.0.0
npm ERR!   at location: /Users/jbaz/code-work/2023/remix-compute/packages/edge-demo-site
```

**Comment by nickytonline** [comment]
@juanpprieto, hmmm, that could be a bug with context.

You can update the `dev` command to `remix watch`. I'll update the dev command for the demo site. As the remix dev command says, the dev server doesn't work for custom servers, i.e. not a node.js environment.

**Comment by nickytonline** [comment]
If you make changes while debugging, you'll need to do a browser refresh if you make UI changes. For Edge function changes, the next request will pick up the latest changes.

**Comment by serhalp** [comment]
@juanpprieto @jtaccinelli We're sorry you didn't get a prompt response here. I hope you were able to resolve your issue. Since this issue is quite stale, I'm going to close it, but please feel free to open a new issue with repro steps if you're still having issues, or (even better) seek help at https://answers.netlify.com/. Thanks.
